from .auth import auth_bp
from .user import user_bp
from .expense import expense_bp
from .budget import budget_bp
from .goal import goal_bp
from .income import income_bp
from .recurring_expense import recurring_expense_bp
from .insights import insights_bp
from .mock_bank import mock_bank_bp
from .notifications import notifications_bp
from .voice import voice_bp